// src/config/config.js
const VERSION = import.meta.env.VITE_API_VERSION;

export const API_ENDPOINTS = {
  EXPORT: `${VERSION}/export`,
  // Komponen
  CPS: `${VERSION}/cps`,
  UVPYS: `${VERSION}/uvpys`,
  UVPPS: `${VERSION}/uvpps`,
  UVUCS: `${VERSION}/uvucs`,
  UICHS: `${VERSION}/uichs`,
  RASIO_REFS: `${VERSION}/rasio_refs`,
  CVMS: `${VERSION}/cvms`,
  CP: `${VERSION}/cp`,
  UVPY: `${VERSION}/uvpy`,
  UVPP: `${VERSION}/uvpp`,
  UVUC: `${VERSION}/uvuc`,
  UICH: `${VERSION}/uich`,
  RASIO_REF: `${VERSION}/rasio_ref`,
  CVM: `${VERSION}/cvm`,
  // SUT
  CPS_SUT: `${VERSION}/cps_sut`,
  UVPYS_SUT: `${VERSION}/uvpys_sut`,
  UVPPS_SUT: `${VERSION}/uvpps_sut`,
  UVUCS_SUT: `${VERSION}/uvucs_sut`,
  UICHS_SUT: `${VERSION}/uichs_sut`,
  RASIO_REFS_SUT: `${VERSION}/rasio_refs_sut`,
  CVMS_SUT: `${VERSION}/cvms_sut`,
  CP_SUT: `${VERSION}/cp_sut`,
  UVPY_SUT: `${VERSION}/uvpy_sut`,
  UVPP_SUT: `${VERSION}/uvpp_sut`,
  UVUC_SUT: `${VERSION}/uvuc_sut`,
  UICH_SUT: `${VERSION}/uich_sut`,
  RASIO_REF_SUT: `${VERSION}/rasio_ref_sut`,
  CVM_SUT: `${VERSION}/cvm_sut`,

  // Tambahkan endpoint lain di sini
};

export const komponens = [
  ["1", "Pengeluaran Konsumsi Rumahtangga"],
  ["1.a", "Makanan dan Minuman, Selain Restoran"],
  ["1.b", "Pakaian, Alas Kaki dan Jasa Perawatannya"],
  ["1.c", "Perumahan dan Perlengkapan Rumahtangga"],
  ["1.d", "Kesehatan dan Pendidikan"],
  ["1.e", "Transportasi dan Komunikasi"],
  ["1.f", "Restoran dan Hotel"],
  ["1.g", "Lainnya"],
  ["2", "Pengeluaran Konsumsi LNPRT"],
  ["3", "Pengeluaran Konsumsi Pemerintah"],
  ["3.a", "Konsumsi Kolektif"],
  ["3.b", "Konsumsi Individu"],
  ["4", "Pembentukan Modal Tetap Bruto"],
  ["4.a", "Bangunan"],
  ["4.b", "Mesin dan Perlengkapan"],
  ["4.c", "Kendaraan"],
  ["4.d", "Peralatan Lainnya"],
  ["4.e", "CBR"],
  ["4.f", "Produk Kekayaan Intelektual"],
  ["5", "Perubahan Inventori"],
  ["6", "Ekspor Barang dan Jasa"],
  ["6.a", "Barang (Ekspor)"],
  ["6.a.1", "Barang Nonmigas (Ekspor)"],
  ["6.a.2", "Barang Migas (Ekspor)"],
  ["6.b", "Jasa (Ekspor)"],
  ["7", "Impor Barang dan Jasa"],
  ["7.a", "Barang (Impor)"],
  ["7.a.1", "Barang Nonmigas (Impor)"],
  ["7.a.2", "Barang Migas (Impor)"],
  ["7.b", "Jasa (Impor)"],
  ["8", "Diskrepansi Statistik"],
  ["9", "Produk Domestik Bruto"],
];
